---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependecias do sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - mysql-server
        - python-mysqldb
        - php5-mysql